# site settings
title: bigAI
subtitle: at Brown
description: Brown Integrated General Artifical Intelligence
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "bigai.cs.brown.edu" # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 25


# build settings
markdown: kramdown

sass:
  style: compressed
