# site settings
title: bigAI
subtitle: at Brown
description: Brown Integrative, General Artificial Intelligence
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "bigai.cs.brown.edu" # the base hostname & protocol for your site

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 25


# build settings
# permalink: pretty
markdown: kramdown
mathjax: true
encoding: utf-8
sass:
  style: compressed

plugins: ['jekyll-twitter-plugin']
